/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AudioClip {
  'data' : Uint8Array,
  'user' : Principal,
  'timestamp' : Time,
}
export interface ChatMessage {
  'content' : string,
  'sender' : Principal,
  'timestamp' : Time,
}
export interface FollowerCount { 'followers' : bigint, 'following' : bigint }
export interface GiftItem {
  'id' : bigint,
  'cost' : bigint,
  'icon' : string,
  'name' : string,
}
export interface GiftTransaction {
  'recipient' : Principal,
  'sender' : Principal,
  'timestamp' : Time,
  'giftId' : bigint,
}
export interface Group {
  'id' : bigint,
  'owner' : Principal,
  'name' : string,
  'createdAt' : Time,
  'description' : [] | [string],
}
export interface MicRequest { 'user' : Principal, 'requestedAt' : Time }
export interface Room {
  'id' : bigint,
  'title' : string,
  'owner' : Principal,
  'createdAt' : Time,
  'description' : [] | [string],
}
export type Time = bigint;
export interface UserProfile {
  'displayName' : string,
  'createdAt' : Time,
  'avatarUrl' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptMicRequest' : ActorMethod<[bigint, Principal], undefined>,
  'addBalance' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createGroup' : ActorMethod<[string, [] | [string]], bigint>,
  'createRoom' : ActorMethod<[string, [] | [string]], bigint>,
  'follow' : ActorMethod<[Principal], undefined>,
  'generateAudienceToken' : ActorMethod<[bigint, string], string>,
  'generateHostToken' : ActorMethod<[bigint, string], string>,
  'getAllRooms' : ActorMethod<[], Array<Room>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getAudioClips' : ActorMethod<[bigint], Array<AudioClip>>,
  'getBalance' : ActorMethod<[], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentMicHolder' : ActorMethod<[bigint], [] | [Principal]>,
  'getFollowerCount' : ActorMethod<[Principal], FollowerCount>,
  'getGiftCatalog' : ActorMethod<[], Array<GiftItem>>,
  'getGiftHistory' : ActorMethod<[Principal], Array<GiftTransaction>>,
  'getGroup' : ActorMethod<[bigint], [] | [Group]>,
  'getGroupMembers' : ActorMethod<[bigint], Array<Principal>>,
  'getGroupMessages' : ActorMethod<[bigint], Array<ChatMessage>>,
  'getMessages' : ActorMethod<[bigint], Array<ChatMessage>>,
  'getMicQueue' : ActorMethod<[bigint], Array<MicRequest>>,
  'getRoom' : ActorMethod<[bigint], [] | [Room]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFollowing' : ActorMethod<[Principal, Principal], boolean>,
  'isGroupMember' : ActorMethod<[bigint, Principal], boolean>,
  'joinGroup' : ActorMethod<[bigint], undefined>,
  'leaveGroup' : ActorMethod<[bigint], undefined>,
  'listGroups' : ActorMethod<[], Array<Group>>,
  'recordAudioClip' : ActorMethod<[bigint, Uint8Array], undefined>,
  'requestMic' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendGift' : ActorMethod<[Principal, bigint], undefined>,
  'sendGroupMessage' : ActorMethod<[bigint, string], undefined>,
  'sendMessage' : ActorMethod<[bigint, string], undefined>,
  'storeZegoCredentials' : ActorMethod<[string, string], undefined>,
  'unfollow' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];