/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Room = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'createdAt' : Time,
  'description' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'createdAt' : Time,
  'avatarUrl' : IDL.Opt(IDL.Text),
});
export const AudioClip = IDL.Record({
  'data' : IDL.Vec(IDL.Nat8),
  'user' : IDL.Principal,
  'timestamp' : Time,
});
export const FollowerCount = IDL.Record({
  'followers' : IDL.Nat,
  'following' : IDL.Nat,
});
export const GiftItem = IDL.Record({
  'id' : IDL.Nat,
  'cost' : IDL.Nat,
  'icon' : IDL.Text,
  'name' : IDL.Text,
});
export const GiftTransaction = IDL.Record({
  'recipient' : IDL.Principal,
  'sender' : IDL.Principal,
  'timestamp' : Time,
  'giftId' : IDL.Nat,
});
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Time,
});
export const MicRequest = IDL.Record({
  'user' : IDL.Principal,
  'requestedAt' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptMicRequest' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'addBalance' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createRoom' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [IDL.Nat], []),
  'follow' : IDL.Func([IDL.Principal], [], []),
  'generateZegoKitToken' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
  'getAllRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAudioClips' : IDL.Func([IDL.Nat], [IDL.Vec(AudioClip)], ['query']),
  'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentMicHolder' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(IDL.Principal)],
      ['query'],
    ),
  'getFollowerCount' : IDL.Func([IDL.Principal], [FollowerCount], ['query']),
  'getGiftCatalog' : IDL.Func([], [IDL.Vec(GiftItem)], ['query']),
  'getGiftHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(GiftTransaction)],
      ['query'],
    ),
  'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
  'getMicQueue' : IDL.Func([IDL.Nat], [IDL.Vec(MicRequest)], ['query']),
  'getRoom' : IDL.Func([IDL.Nat], [IDL.Opt(Room)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFollowing' : IDL.Func(
      [IDL.Principal, IDL.Principal],
      [IDL.Bool],
      ['query'],
    ),
  'recordAudioClip' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat8)], [], []),
  'requestMic' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendGift' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'storeZegoCredentials' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'unfollow' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Room = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'createdAt' : Time,
    'description' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'createdAt' : Time,
    'avatarUrl' : IDL.Opt(IDL.Text),
  });
  const AudioClip = IDL.Record({
    'data' : IDL.Vec(IDL.Nat8),
    'user' : IDL.Principal,
    'timestamp' : Time,
  });
  const FollowerCount = IDL.Record({
    'followers' : IDL.Nat,
    'following' : IDL.Nat,
  });
  const GiftItem = IDL.Record({
    'id' : IDL.Nat,
    'cost' : IDL.Nat,
    'icon' : IDL.Text,
    'name' : IDL.Text,
  });
  const GiftTransaction = IDL.Record({
    'recipient' : IDL.Principal,
    'sender' : IDL.Principal,
    'timestamp' : Time,
    'giftId' : IDL.Nat,
  });
  const ChatMessage = IDL.Record({
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Time,
  });
  const MicRequest = IDL.Record({
    'user' : IDL.Principal,
    'requestedAt' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptMicRequest' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'addBalance' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createRoom' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [IDL.Nat], []),
    'follow' : IDL.Func([IDL.Principal], [], []),
    'generateZegoKitToken' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
    'getAllRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAudioClips' : IDL.Func([IDL.Nat], [IDL.Vec(AudioClip)], ['query']),
    'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentMicHolder' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(IDL.Principal)],
        ['query'],
      ),
    'getFollowerCount' : IDL.Func([IDL.Principal], [FollowerCount], ['query']),
    'getGiftCatalog' : IDL.Func([], [IDL.Vec(GiftItem)], ['query']),
    'getGiftHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(GiftTransaction)],
        ['query'],
      ),
    'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
    'getMicQueue' : IDL.Func([IDL.Nat], [IDL.Vec(MicRequest)], ['query']),
    'getRoom' : IDL.Func([IDL.Nat], [IDL.Opt(Room)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFollowing' : IDL.Func(
        [IDL.Principal, IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'recordAudioClip' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat8)], [], []),
    'requestMic' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendGift' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'storeZegoCredentials' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'unfollow' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };